# Generated by Django 5.0.4 on 2024-05-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsattempt',
            name='status',
            field=models.CharField(default='Отправлено', max_length=200, verbose_name='Статус попытки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='periodicity',
            field=models.CharField(choices=[('Раз в день', 'Once a Day'), ('Раз в неделю', 'Once a Week'), ('Раз в месяц', 'Once a Month')], default='Раз в день', max_length=20, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='status',
            field=models.CharField(choices=[('Завершена', 'Completed'), ('Создана', 'Created'), ('Запущена', 'Started')], default='Создана', max_length=20, verbose_name='Статус рассылки'),
        ),
    ]
