# Generated by Django 5.0.4 on 2024-06-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_clientservice_owner_mailingsettings_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'ordering': ('date_time',), 'permissions': (('set_settings_deactivate', 'Can deactivate settings'),), 'verbose_name': 'Настройка рассылки', 'verbose_name_plural': 'Настройки рассылки'},
        ),
    ]
