# Generated by Django 5.0.4 on 2024-06-04 20:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_alter_mailingsettings_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageLetter',
            new_name='Message',
        ),
    ]
